# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'lineup.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QMainWindow, QMenu,
    QMenuBar, QScrollArea, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 700)
        self.actionHome = QAction(MainWindow)
        self.actionHome.setObjectName(u"actionHome")
        self.actionYoruAbyssA = QAction(MainWindow)
        self.actionYoruAbyssA.setObjectName(u"actionYoruAbyssA")
        self.actionYoruAbyssB = QAction(MainWindow)
        self.actionYoruAbyssB.setObjectName(u"actionYoruAbyssB")
        self.actionYoruAscentA = QAction(MainWindow)
        self.actionYoruAscentA.setObjectName(u"actionYoruAscentA")
        self.actionYoruAscentB = QAction(MainWindow)
        self.actionYoruAscentB.setObjectName(u"actionYoruAscentB")
        self.actionYoruBindA = QAction(MainWindow)
        self.actionYoruBindA.setObjectName(u"actionYoruBindA")
        self.actionYoruBindB = QAction(MainWindow)
        self.actionYoruBindB.setObjectName(u"actionYoruBindB")
        self.actionYoruBreezeA = QAction(MainWindow)
        self.actionYoruBreezeA.setObjectName(u"actionYoruBreezeA")
        self.actionYoruBreezeB = QAction(MainWindow)
        self.actionYoruBreezeB.setObjectName(u"actionYoruBreezeB")
        self.actionYoruFractureA = QAction(MainWindow)
        self.actionYoruFractureA.setObjectName(u"actionYoruFractureA")
        self.actionYoruFractureB = QAction(MainWindow)
        self.actionYoruFractureB.setObjectName(u"actionYoruFractureB")
        self.actionYoruHavenA = QAction(MainWindow)
        self.actionYoruHavenA.setObjectName(u"actionYoruHavenA")
        self.actionYoruHavenB = QAction(MainWindow)
        self.actionYoruHavenB.setObjectName(u"actionYoruHavenB")
        self.actionYoruHavenC = QAction(MainWindow)
        self.actionYoruHavenC.setObjectName(u"actionYoruHavenC")
        self.actionYoruIceboxA = QAction(MainWindow)
        self.actionYoruIceboxA.setObjectName(u"actionYoruIceboxA")
        self.actionYoruIceboxB = QAction(MainWindow)
        self.actionYoruIceboxB.setObjectName(u"actionYoruIceboxB")
        self.actionYoruLotusA = QAction(MainWindow)
        self.actionYoruLotusA.setObjectName(u"actionYoruLotusA")
        self.actionYoruLotusB = QAction(MainWindow)
        self.actionYoruLotusB.setObjectName(u"actionYoruLotusB")
        self.actionYoruLotusC = QAction(MainWindow)
        self.actionYoruLotusC.setObjectName(u"actionYoruLotusC")
        self.actionYoruPearlA = QAction(MainWindow)
        self.actionYoruPearlA.setObjectName(u"actionYoruPearlA")
        self.actionBYoruPearlB = QAction(MainWindow)
        self.actionBYoruPearlB.setObjectName(u"actionBYoruPearlB")
        self.actionYoruSplitA = QAction(MainWindow)
        self.actionYoruSplitA.setObjectName(u"actionYoruSplitA")
        self.actionYoruSplitB = QAction(MainWindow)
        self.actionYoruSplitB.setObjectName(u"actionYoruSplitB")
        self.actionYoruSunsetA = QAction(MainWindow)
        self.actionYoruSunsetA.setObjectName(u"actionYoruSunsetA")
        self.actionYoruSunsetB = QAction(MainWindow)
        self.actionYoruSunsetB.setObjectName(u"actionYoruSunsetB")
        self.actionYoruAbyssMid = QAction(MainWindow)
        self.actionYoruAbyssMid.setObjectName(u"actionYoruAbyssMid")
        self.actionYoruAscentMid = QAction(MainWindow)
        self.actionYoruAscentMid.setObjectName(u"actionYoruAscentMid")
        self.actionYoruBreezeMid = QAction(MainWindow)
        self.actionYoruBreezeMid.setObjectName(u"actionYoruBreezeMid")
        self.actionYoruFractureMid = QAction(MainWindow)
        self.actionYoruFractureMid.setObjectName(u"actionYoruFractureMid")
        self.actionYoruIceboxMid = QAction(MainWindow)
        self.actionYoruIceboxMid.setObjectName(u"actionYoruIceboxMid")
        self.actionYoruPearlMid = QAction(MainWindow)
        self.actionYoruPearlMid.setObjectName(u"actionYoruPearlMid")
        self.actionYoruSplitMid = QAction(MainWindow)
        self.actionYoruSplitMid.setObjectName(u"actionYoruSplitMid")
        self.actionYoruSunsetMid = QAction(MainWindow)
        self.actionYoruSunsetMid.setObjectName(u"actionYoruSunsetMid")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 100, 100))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 98, 98))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 26))
        self.menuAgents = QMenu(self.menubar)
        self.menuAgents.setObjectName(u"menuAgents")
        self.menuYoru = QMenu(self.menuAgents)
        self.menuYoru.setObjectName(u"menuYoru")
        self.menuAbyss_2 = QMenu(self.menuYoru)
        self.menuAbyss_2.setObjectName(u"menuAbyss_2")
        self.menuAscent_2 = QMenu(self.menuYoru)
        self.menuAscent_2.setObjectName(u"menuAscent_2")
        self.menuBind = QMenu(self.menuYoru)
        self.menuBind.setObjectName(u"menuBind")
        self.menuBreeze = QMenu(self.menuYoru)
        self.menuBreeze.setObjectName(u"menuBreeze")
        self.menuFracture = QMenu(self.menuYoru)
        self.menuFracture.setObjectName(u"menuFracture")
        self.menuHaven = QMenu(self.menuYoru)
        self.menuHaven.setObjectName(u"menuHaven")
        self.menuIcebox = QMenu(self.menuYoru)
        self.menuIcebox.setObjectName(u"menuIcebox")
        self.menuLotus = QMenu(self.menuYoru)
        self.menuLotus.setObjectName(u"menuLotus")
        self.menuPearl = QMenu(self.menuYoru)
        self.menuPearl.setObjectName(u"menuPearl")
        self.menuSplit = QMenu(self.menuYoru)
        self.menuSplit.setObjectName(u"menuSplit")
        self.menuSunset = QMenu(self.menuYoru)
        self.menuSunset.setObjectName(u"menuSunset")
        self.menuHome = QMenu(self.menubar)
        self.menuHome.setObjectName(u"menuHome")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuAgents.menuAction())
        self.menuAgents.addAction(self.menuYoru.menuAction())
        self.menuYoru.addAction(self.menuAbyss_2.menuAction())
        self.menuYoru.addAction(self.menuAscent_2.menuAction())
        self.menuYoru.addAction(self.menuBind.menuAction())
        self.menuYoru.addAction(self.menuBreeze.menuAction())
        self.menuYoru.addAction(self.menuFracture.menuAction())
        self.menuYoru.addAction(self.menuHaven.menuAction())
        self.menuYoru.addAction(self.menuIcebox.menuAction())
        self.menuYoru.addAction(self.menuLotus.menuAction())
        self.menuYoru.addAction(self.menuPearl.menuAction())
        self.menuYoru.addAction(self.menuSplit.menuAction())
        self.menuYoru.addAction(self.menuSunset.menuAction())
        self.menuAbyss_2.addAction(self.actionYoruAbyssA)
        self.menuAbyss_2.addAction(self.actionYoruAbyssMid)
        self.menuAbyss_2.addAction(self.actionYoruAbyssB)
        self.menuAscent_2.addAction(self.actionYoruAscentA)
        self.menuAscent_2.addAction(self.actionYoruAscentMid)
        self.menuAscent_2.addAction(self.actionYoruAscentB)
        self.menuBind.addAction(self.actionYoruBindA)
        self.menuBind.addAction(self.actionYoruBindB)
        self.menuBreeze.addAction(self.actionYoruBreezeA)
        self.menuBreeze.addAction(self.actionYoruBreezeMid)
        self.menuBreeze.addAction(self.actionYoruBreezeB)
        self.menuFracture.addAction(self.actionYoruFractureA)
        self.menuFracture.addAction(self.actionYoruFractureMid)
        self.menuFracture.addAction(self.actionYoruFractureB)
        self.menuHaven.addAction(self.actionYoruHavenA)
        self.menuHaven.addAction(self.actionYoruHavenB)
        self.menuHaven.addAction(self.actionYoruHavenC)
        self.menuIcebox.addAction(self.actionYoruIceboxA)
        self.menuIcebox.addAction(self.actionYoruIceboxMid)
        self.menuIcebox.addAction(self.actionYoruIceboxB)
        self.menuLotus.addAction(self.actionYoruLotusA)
        self.menuLotus.addAction(self.actionYoruLotusB)
        self.menuLotus.addAction(self.actionYoruLotusC)
        self.menuPearl.addAction(self.actionYoruPearlA)
        self.menuPearl.addAction(self.actionYoruPearlMid)
        self.menuPearl.addAction(self.actionBYoruPearlB)
        self.menuSplit.addAction(self.actionYoruSplitA)
        self.menuSplit.addAction(self.actionYoruSplitMid)
        self.menuSplit.addAction(self.actionYoruSplitB)
        self.menuSunset.addAction(self.actionYoruSunsetA)
        self.menuSunset.addAction(self.actionYoruSunsetMid)
        self.menuSunset.addAction(self.actionYoruSunsetB)
        self.menuHome.addAction(self.actionHome)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionHome.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.actionYoruAbyssA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruAbyssB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruAscentA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruAscentB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruBindA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruBindB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruBreezeA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruBreezeB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruFractureA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruFractureB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruHavenA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruHavenB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruHavenC.setText(QCoreApplication.translate("MainWindow", u"C site", None))
        self.actionYoruIceboxA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruIceboxB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruLotusA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruLotusB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruLotusC.setText(QCoreApplication.translate("MainWindow", u"C site", None))
        self.actionYoruPearlA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionBYoruPearlB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruSplitA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruSplitB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruSunsetA.setText(QCoreApplication.translate("MainWindow", u"A site", None))
        self.actionYoruSunsetB.setText(QCoreApplication.translate("MainWindow", u"B site", None))
        self.actionYoruAbyssMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.actionYoruAscentMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.actionYoruBreezeMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.actionYoruFractureMid.setText(QCoreApplication.translate("MainWindow", u"Mid/Deffender spawn", None))
        self.actionYoruIceboxMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.actionYoruPearlMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.actionYoruSplitMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.actionYoruSunsetMid.setText(QCoreApplication.translate("MainWindow", u"Mid", None))
        self.menuAgents.setTitle(QCoreApplication.translate("MainWindow", u"Agents", None))
        self.menuYoru.setTitle(QCoreApplication.translate("MainWindow", u"Yoru", None))
        self.menuAbyss_2.setTitle(QCoreApplication.translate("MainWindow", u"Abyss", None))
        self.menuAscent_2.setTitle(QCoreApplication.translate("MainWindow", u"Ascent", None))
        self.menuBind.setTitle(QCoreApplication.translate("MainWindow", u"Bind", None))
        self.menuBreeze.setTitle(QCoreApplication.translate("MainWindow", u"Breeze", None))
        self.menuFracture.setTitle(QCoreApplication.translate("MainWindow", u"Fracture", None))
        self.menuHaven.setTitle(QCoreApplication.translate("MainWindow", u"Haven", None))
        self.menuIcebox.setTitle(QCoreApplication.translate("MainWindow", u"Icebox", None))
        self.menuLotus.setTitle(QCoreApplication.translate("MainWindow", u"Lotus", None))
        self.menuPearl.setTitle(QCoreApplication.translate("MainWindow", u"Pearl", None))
        self.menuSplit.setTitle(QCoreApplication.translate("MainWindow", u"Split", None))
        self.menuSunset.setTitle(QCoreApplication.translate("MainWindow", u"Sunset", None))
        self.menuHome.setTitle(QCoreApplication.translate("MainWindow", u"Home", None))
    # retranslateUi

